export default {
    toastMessage: "div.Toastify",
    validationError: "p.Mui-error",
    phoneValidationError: ".phoneRequire",
    navNewActivityBtn: "button.navbarBtn",
    navYourWorkflowBtn: ".WorkflowBtn.navbarBtn",
    navOptions: "[role='menuitem']",
    dropdownOptions: "[role='option']",
    submitButton: "#submit-login",
    dropdownOptionButtons: "[role='button']",
    dialogBtns: "[role='dialog'] button",
    emailField: "#email",
    name: "#name",
    errorUnderLine: ".MuiInput-underline.Mui-error",
    pageHeading: ".GarrageInfo.header__title__ro",
    submitConfirmText: ".SubmitConfirmText p",
    customerToastMessage: ".SubmitConfirmText p.para",
    confirmModalbutton: "button.CustomizeSwalConfirmButton",
    navLinks: "a.nav__link",
    noDataContainer: "div.no__data__center",
    closeModalBtn: "div.dialog__header__container button",
    tabButtons: "button[id*='vertical-tab-']",
    skeletonLoaders: "span.MuiSkeleton-pulse",
}