export default {
    creates: {
        addPartsTextButton: ".main__content__jobboard > div > div > div.MuiGrid-root:nth-child(3) > div > div.MuiGrid-container button",
        searchPartsMultiple: "#partName",
        addedPartsTextButton: "div.MuiGrid-justify-content-xs-flex-end button",
        addSuppliesTextButton: ".main__content__jobboard > div > div > div.MuiGrid-root:nth-child(3) > div > div.MuiGrid-container button",
        searchSuppliesMultiple: "#item",
        addedSuppliesTextButton: "div.MuiGrid-justify-content-xs-flex-end button",
        addLaborsTextButton: ".main__content__jobboard > div > div > div.MuiGrid-root:nth-child(3) > div > div.MuiGrid-container button",
        laborSearch: "#category",
        laborTypes: "div.MuiGrid-container.MuiGrid-item div.MuiChip-clickable",
        addedLaborsTextButton: "div.MuiGrid-justify-content-xs-flex-end button",
        notes: "textarea#notes",
        tax: "input[name='tax']",
        discountToggleTextButton: "button.toggle_btn",
        discount: "input[name='discount']",
        generateCOBtn: "#addEstimate",
        "@createQuickChckOut": 200,
        generateInvoiceBtn: "div.main__content__jobboard > div > div > div:nth-child(7) .MuiGrid-justify-content-xs-flex-end button",
        successMsg: "#swal2-title",
        okSuccessBtn: ".CustomizeSwalConfirmButton"
    },
    quickCheckoutBtn: "a.quickcheckoutbtn",
    searchedItem: "ul > li.MuiListItem-gutters",
    convertToBtns: ".MuiGrid-justify-content-xs-flex-end button.MuiButtonBase-root",
    submitBtn: ".MuiGrid-justify-content-xs-flex-end button.MuiButtonBase-root",
    searchCustomer: "#key",
    addCustomerBtn: ".addCustomer",
    searchByDropdown: ".MuiPaper-elevation1 div.MuiSelect-selectMenu",
    customerData: "ul > div",
    vehicleData: "div.MuiCardContent-root",
    selectedcustomerData: "div.MuiCardContent-root",
    selectedvehicleData: "div.MuiCardContent-root",
    previewField: ".nameValue p.name",
    previewFieldValue: "p.value",
    previewConditionName: ".topAccordion .Name",
    previewConditionValue: ".topAccordion .Value",
    dropdownOptionButtons: ".MuiListItem-button[role='button']",
    dropdownVehicleButtons: "span",
    jobTypes: "div.MuiChip-clickable",
    otherJobType: "#otherJobType",
    turnaroundDate: "#turnaroundDate",
    turnaroundTime: "#turnaroundTime",
    manHours: "#manHours",
    tax: "#tax",
    discount: "#discount",
    problemSearch: "#input-with-icon-textfield",
    problems: "div.MuiGrid-direction-xs-column span.MuiFormControlLabel-label",
    notes: "textarea#notes",
    discountToggle: "button.toggle_btn",
    problemTypeBtn: ".MuiGrid-justify-content-xs-space-between button",
    addPartsBtns: "button.MuiButton-fullWidth",
    generateEstimateBtn: "#addEstimate",
    successTitle: "#swal2-title",
    okBtn: "button.CustomizeSwalConfirmButton",
    vehicleMakeDropdown: "#vehicleMake",
    vehicleModelDropdown: "#vehicleModel",
    vehicleModelYearDropdown: "#modelYear",
    catagoryCheck: "input[name='partCategory']",
    searchPart: "#partName",
    vendorDropddown: "#vendor",
    laborSearch: "#category",
    supplySearch: "#item",
    vendorDropdown: "#vendor"
}